@startmindmap

+ Сайт\n**litres.ru**

++ Регистрация/авторизация
+++ Телефон
+++ email
+++ соцсети

++ Найти книгу
+++ по названию
+++ по серии
+++ по автору
+++ по жанру
+++ по издательству

++ Отфильтровать результат поиска
+++ формат
++++ текст
++++ подкасты
+++ язык
+++ рейтинг
+++ доступно по подписке
+++ доступно в абонементе
+++ автор Литрес

++ Работа с корзиной
+++ Добавить товар в корзину
++++ Печатный вариант
++++ Электронный вариант
+++ Очистить/отредактировать корзину
+++ Оформить заказ
+++ Оплатить товары в корзине
++++ Кредитной/бонусной картой
++++ Через телефон
+++ Получить покупку
++++ Электронный вариант
+++++ Скачать
+++++ Добавить на свое устройство
++++ Бумажный вариант
+++++ Заказать доставку
+++++ Оформить самовывоз

-- Работа со счетом
--- Добавить/удалить кредитную/бонусную карту
--- Отобразить состояние счета
--- Пополнить счет
--- Показать историю операций

-- Стать автором Литрес

-- Обратиться в службу поддержки

-- Работа с профилем
--- Настройки входа
---- Изменить телефон/почту
---- Привязать соцсеть
--- Изменить личную информацию
--- Работа с уведомлениями
--- Работа с рассылкой

-- Работа с абонементом
--- Выбрать книгу
--- Привязать карту
--- Отобразить информацию по абонементу
--- Обратиться в приоритетную поддержку

-- Читать/слушать книгу онлайн

-- Загрузить свою книгу

-- Купить подарок
--- Подписка
--- Абонемент
--- Сертификат на сумму

@endmindmap
