@startmindmap

+ **litres.ru**

++ Регистрация/авторизация
+++ Телефон
+++ email
+++ соцсети

++ Найти книгу
+++ Применить фильтрацию
++++ Печатная книга
++++ Электронная книга
++++ Аудиокнига

++ Купить
+++ Книгу
++++ Печатная книга
++++ Электронная книга
++++ Аудиокнига
+++ Подписку
+++ Абонемент
+++ Подарок

++ Получить покупку
+++ Скачать
+++ Заказать доставку
+++ Оформить самовывоз

++ Читать книгу онлайн
++ Слушать книгу онлайн

++ Корзина
+++ Показать список товаров
+++ Рассчитать скидку
+++ Очистить корзину

-- Работа с профилем
--- Пополнить счет
--- Отобразить состояние счета
--- Уведомления
---- Отобразить список уведомлений
--- Информация для входа
---- Изменить телефон/почту
---- Привязать соцсеть
--- Обо мне
---- Добавить/убрать фотографию
---- Добавить/убрать ФИО, дату рождения 
---- Показать политику конфиденциальности
--- История операций
--- Мои способы оплаты
---- Добавить/удалить карту
--- Бонусные карты
---- Добавить/удалить бонусную карту
--- Рассылки
---- Добавить/удалить список рассылок
--- Покупки друзей
---- Отобразить доступную сумму
--- ЛитРес: Абонемент
---- Выбрать книги
---- Привязать карту
---- Отобразить информацию по абонементу
---- Обратиться в приоритетную поддержку
--- Стать автором Литрес
--- Служба поддержки
--- Выход

-- Нотификация
--- Показать на сайте\n/(отослать на почту)
---- Доступны новые книги
---- Доступны скидки
---- Книга появилась в наличии

-- Дополнительно
--- Добавить книги с моего компьютера

@endmindmap
